import bcrypt from 'bcryptjs'

const data = {
    users: [{
            name: 'Basir',
            email: 'admin@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@example.com',
            password: bcrypt.hashSync('123456'),
            isAdmin: false,
        },
    ],
    products: [{
            // _id: '1',
            name: 'Lofi Song',
            slug: 'lofi-song',
            category: 'cartoon',
            image: '/images/ctn(1).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'Poster',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        }, {
            // _id: '1',
            name: 'PIKACHU',
            slug: 'pikachu',
            category: 'cartoon',
            image: '/images/ctn(2).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Bunny',
            slug: 'bunny',
            category: 'cartoon',
            image: '/images/ctn(3).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Goku-1',
            slug: 'goku-1',
            category: 'cartoon',
            image: '/images/ctn(4).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Banana Man',
            slug: 'banana-man',
            category: 'cartoon',
            image: '/images/ctn(5).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'God Of War',
            slug: 'god-of-war-1',
            category: 'game',
            image: '/images/gm(1).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Cratos',
            slug: 'god-of-war-2',
            category: 'game',
            image: '/images/gm(2).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Joker-1',
            slug: 'joker-1',
            category: 'game',
            image: '/images/gm(3).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Black Panther',
            slug: 'black-panther',
            category: 'MCU',
            image: '/images/mcu(1).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Spider Man 1',
            slug: 'spider-man-1',
            category: 'MCU',
            image: '/images/mcu(2).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Spider Man 2',
            slug: 'spider-man-2',
            category: 'MCU',
            image: '/images/mcu(3).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Spider Man 3',
            slug: 'spider-man-3',
            category: 'Shirts',
            image: '/images/mcu(4).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Spider Man 4',
            slug: 'spider-man-4',
            category: 'MCU',
            image: '/images/mcu(5).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Spider Man 5',
            slug: 'spider-man-5',
            category: 'MCU',
            image: '/images/mcu(6).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Spider Man 6',
            slug: 'spider-man-6',
            category: 'MCU',
            image: '/images/mcu(7).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Iron Man 7',
            slug: 'iron-man',
            category: 'MCU',
            image: '/images/mcu(8).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Civil War ',
            slug: 'civil-war',
            category: 'MCU',
            image: '/images/mcu(9).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {

            name: 'Thor1',
            slug: 'thor1',
            category: 'MCU',
            image: '/images/mcu(10).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {

            name: 'Venom',
            slug: 'venom',
            category: 'MCU',
            image: '/images/mcu(11).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Thor',
            slug: 'thor',
            category: 'MCU',
            image: '/images/mcu(12).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Spider Man-7',
            slug: 'spider-man-7',
            category: 'MCU',
            image: '/images/mcu(13).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 1',
            slug: 'money-heist-1',
            category: 'movies',
            image: '/images/mh(1).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 2',
            slug: 'money-heist-2',
            category: 'movies',
            image: '/images/mh(2).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 3',
            slug: 'money-heist-3',
            category: 'movies',
            image: '/images/mh(3).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 4',
            slug: 'money-heist-4',
            category: 'movies',
            image: '/images/mh(4).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 5',
            slug: 'money-heist-5',
            category: 'movies',
            image: '/images/mh(5).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 6',
            slug: 'money-heist-6',
            category: 'movies',
            image: '/images/mh(6).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'movies',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 7',
            slug: 'money-heist-7',
            category: 'movies',
            image: '/images/mh(7).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'movies',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: "Money Heist 8",
            slug: 'money-heist-8',
            category: 'movies',
            image: '/images/mh(8).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 9',
            slug: 'money-heist-9',
            category: 'movies',
            image: '/images/mh(9).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Money Heist 10',
            slug: 'money-heist-10',
            category: 'movies',
            image: '/images/mh(10).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Holy Cross',
            slug: 'holy-cross',
            category: 'quotes',
            image: '/images/mtv(1).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Good And Great',
            slug: 'good-and-great',
            category: 'quotes',
            image: '/images/mtv(2).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            // _id: '1',
            name: 'Be Positive',
            slug: 'b-positive',
            category: 'quotes',
            image: '/images/mtv(3).jpg', // 679px × 829px
            price: 120,
            countInStock: 10,
            brand: 'POSTER',
            rating: 4.5,
            numReviews: 10,
            description: 'High Quality Poster',
        },
        {
            name: 'Hanuman',
            slug: 'hanuman',
            category: 'religious',
            image: '/images/r1.jpg',
            price: 199,
            countInStock: 12,
            brand: 'poster bazaar',
            rating: 4.8,
            numReviews: 19,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Shiva',
            slug: 'shiva',
            category: 'religious',
            image: '/images/r2.jpg',
            price: 299,
            countInStock: 19,
            brand: 'poster bazaar',
            rating: 4.2,
            numReviews: 29,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Krishna',
            slug: 'krishna',
            category: 'religious',
            image: '/images/r3.jpg',
            price: 299,
            countInStock: 32,
            brand: 'poster bazaar',
            rating: 4.9,
            numReviews: 31,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Ganesh',
            slug: 'ganesh',
            category: 'religious',
            image: '/images/r4.jpg',
            price: 199,
            countInStock: 23,
            brand: 'poster bazaar',
            rating: 4.6,
            numReviews: 39,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Hanuman1',
            slug: 'hanuman1',
            category: 'religious',
            image: '/images/r5.jpg',
            price: 199,
            countInStock: 5,
            brand: 'poster bazaar',
            rating: 5.0,
            numReviews: 2,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Shiva1',
            slug: 'shiva1',
            category: 'religious',
            image: '/images/r6.jpg',
            price: 199,
            countInStock: 24,
            brand: 'poster bazaar',
            rating: 4.3,
            numReviews: 40,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Krishna1',
            slug: 'krishna1',
            category: 'religious',
            image: '/images/r7.jpg',
            price: 199,
            countInStock: 42,
            brand: 'poster bazaar',
            rating: 4.5,
            numReviews: 49,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Batman',
            slug: 'batman',
            category: 'Comics',
            image: '/images/c1.jpg',
            price: 199,
            countInStock: 32,
            brand: 'poster bazaar',
            rating: 4.8,
            numReviews: 30,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Aquaman',
            slug: 'aquaman',
            category: 'Comics',
            image: '/images/c2.jpg',
            price: 199,
            countInStock: 26,
            brand: 'poster bazaar',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Joker',
            slug: 'joker',
            category: 'Comics',
            image: '/images/c3.jpg',
            price: 199,
            countInStock: 36,
            brand: 'poster bazaar',
            rating: 4.5,
            numReviews: 40,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Superman',
            slug: 'superman',
            category: 'Comics',
            image: '/images/c4.jpg',
            price: 199,
            countInStock: 33,
            brand: 'poster bazaar',
            rating: 4.9,
            numReviews: 4,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Deadpool',
            slug: 'deadpool',
            category: 'Comics',
            image: '/images/c5.jpg',
            price: 199,
            countInStock: 34,
            brand: 'poster bazaar',
            rating: 4.8,
            numReviews: 20,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Wolverine',
            slug: 'wolverine',
            category: 'Comics',
            image: '/images/c6.jpg',
            price: 199,
            countInStock: 20,
            brand: 'poster bazaar',
            rating: 4.3,
            numReviews: 40,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Spiderman',
            slug: 'spiderman',
            category: 'Comics',
            image: '/images/c7.jpg',
            price: 199,
            countInStock: 20,
            brand: 'poster bazaar',
            rating: 4.7,
            numReviews: 39,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Baki',
            slug: 'baki',
            category: 'Anime',
            image: '/images/a1.jpg',
            price: 199,
            countInStock: 29,
            brand: 'poster bazaar',
            rating: 4.7,
            numReviews: 39,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Goku',
            slug: 'goku',
            category: 'Anime',
            image: '/images/a2.jpg',
            price: 199,
            countInStock: 43,
            brand: 'poster bazaar',
            rating: 4.5,
            numReviews: 45,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Naruto',
            slug: 'naruto',
            category: 'Anime',
            image: '/images/a3.jpg',
            price: 199,
            countInStock: 24,
            brand: 'poster bazaar',
            rating: 4.3,
            numReviews: 40,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Haikyu',
            slug: 'haikyu',
            category: 'Anime',
            image: '/images/a4.jpg',
            price: 199,
            countInStock: 28,
            brand: 'poster bazaar',
            rating: 4.3,
            numReviews: 53,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Levi',
            slug: 'levi',
            category: 'Anime',
            image: '/images/a5.jpg',
            price: 199,
            countInStock: 31,
            brand: 'poster bazaar',
            rating: 4.9,
            numReviews: 11,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Attack of Titan',
            slug: 'attack-of-titan',
            category: 'Anime',
            image: '/images/a6.jpg',
            price: 199,
            countInStock: 25,
            brand: 'poster bazaar',
            rating: 4.2,
            numReviews: 41,
            description: 'high quality wallpaper art with glossy smooth finish',
        },
        {
            name: 'Demon Slayer',
            slug: 'demon-slayer',
            category: 'Anime',
            image: '/images/a7.jpg',
            price: 199,
            countInStock: 45,
            brand: 'poster bazaar',
            rating: 4.3,
            numReviews: 17,
            description: 'high quality wallpaper art with glossy smooth finish',
        }



    ],
};
export default data;